[Addon]
Name=Omaspansion Typed Expander
Comment=Expands omaspansion keys after a configurable prefix
Category=Module
Version=0.1.0
Type=SharedLibrary
Library=omaspansionexpander
OnDemand=False
Configurable=False

[Dependencies]
0=core
